-- Supabase schema for Seismic Roast
-- Run in Supabase SQL editor

create table if not exists public.roast_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.roast_results (
  id bigint generated by default as identity primary key,
  username text not null,
  pay text,
  bnpl text,
  crypto text,
  wallet text,
  seed text,
  roast_title text not null,
  privacy_score int,
  roast_body text,
  seismic_line text,
  created_at timestamptz not null default now()
);

alter table public.roast_users enable row level security;
alter table public.roast_results enable row level security;

-- For client-side writes with anon key
create policy if not exists "allow anon insert roast_users"
on public.roast_users for insert
with check (true);

create policy if not exists "allow anon insert roast_results"
on public.roast_results for insert
with check (true);
